# Generated by Django 2.0.7 on 2018-09-27 10:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metabolization", "0002_reaction_status_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="chemdoodle_json",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=None, null=True
            ),
        ),
    ]
