# Generated by Django 2.0.7 on 2018-09-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabolization', '0003_reaction_chemdoodle_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='chemdoodle_json_error',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
