# Generated by Django 2.0.7 on 2018-10-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabolization', '0004_reaction_chemdoodle_json_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactprocess',
            name='method',
            field=models.CharField(default='rdkit', max_length=32),
        ),
    ]
