# Generated by Django 2.1.2 on 2018-10-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metabolization", "0008_auto_20181005_0917"),
    ]

    operations = [
        migrations.RemoveField(model_name="reactprocess", name="achieved",),
        migrations.RemoveField(model_name="reactprocess", name="method",),
        migrations.RemoveField(model_name="reactprocess", name="method_hash",),
    ]
