# Generated by Django 2.1.2 on 2018-10-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metabolization", "0009_auto_20181009_1602"),
    ]

    operations = [
        migrations.RemoveField(model_name="reaction", name="method_priority",),
    ]
