# Generated by Django 2.1.2 on 2019-06-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_tag'),
        ('metabolization', '0010_remove_reaction_method_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='reaction_tags', to='base.Tag'),
        ),
    ]
