# Generated by Django 2.0.7 on 2018-08-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fragmentation", "0009_auto_20180808_0851"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fragcompareconf",
            name="cosine_min_matched_peaks",
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
