# Generated by Django 2.0.7 on 2018-09-11 12:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragmentation', '0010_auto_20180808_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragsample',
            name='cosine_matrix',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), null=True, size=None),
        ),
    ]
