# Generated by Django 2.0.7 on 2018-09-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fragmentation", "0011_fragsample_cosine_matrix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fragannotationdb",
            name="db_id",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="fragannotationdb",
            name="db_source",
            field=models.CharField(default="unkown", max_length=256),
        ),
        migrations.AlterField(
            model_name="fragannotationdb",
            name="name",
            field=models.CharField(default="", max_length=256),
        ),
    ]
