# Generated by Django 2.1.2 on 2018-10-08 15:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fragmentation", "0012_auto_20180924_1602"),
    ]

    operations = [
        migrations.AddField(
            model_name="fragsample",
            name="mass_delta_double",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.FloatField(), size=None
                ),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="fragsample",
            name="mass_delta_single",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.FloatField(), size=None
                ),
                null=True,
                size=None,
            ),
        ),
    ]
