# Generated by Django 2.1.2 on 2018-10-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fragmentation", "0015_auto_20181009_0956"),
    ]

    operations = [
        migrations.AddField(
            model_name="fragsample",
            name="reaction_mass_max",
            field=models.FloatField(default=0),
        ),
    ]
