# Generated by Django 2.1.2 on 2019-05-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragmentation', '0017_auto_20190406_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragcompareconf',
            name='cosine_threshold',
            field=models.FloatField(default=0.18),
        ),
    ]
