# Generated by Django 2.1.2 on 2019-06-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_tag'),
        ('fragmentation', '0018_auto_20190509_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragsample',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='fragsample_tags', to='base.Tag'),
        ),
    ]
