# Generated by Django 2.2.12 on 2021-01-22 09:47

from django.db import migrations, models
import fragmentation.utils.annotation_status


class Migration(migrations.Migration):

    dependencies = [
        ('fragmentation', '0020_auto_20190727_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragannotationdb',
            name='status',
            field=models.IntegerField(default=fragmentation.utils.annotation_status.AnnotationStatus(0)),
        ),
    ]
