# Generated by Django 2.1.2 on 2018-10-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_molecule_chemdoodle_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
