# Generated by Django 2.1.2 on 2018-10-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_apistatus"),
        ("base", "0007_array1dmodel_array2dmodel"),
    ]

    operations = []
