# Generated by Django 2.1.2 on 2018-11-14 18:22

from django.db import migrations

def create_guest(apps, schema_editor):

    user_guest = {
        'username': 'Guest',
        'email': 'metwork.dev@gmail.com',
        'password': 'AYL6jGBm6R',
    }

    User = apps.get_model('base', 'User')

    if not User.objects.filter(username = user_guest['username']).exists():
        u = User.objects.create(
            username = user_guest['username'],
            email = user_guest['email'])
        u.set_password(user_guest['password'])
        u.save()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_merge_20181012_1234'),
    ]

    operations = [
        migrations.RunPython(create_guest),
    ]
