# Generated by Django 2.2.4 on 2020-05-12 08:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_type', models.IntegerField()),
                ('data_id', models.IntegerField()),
                ('layout', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
