# Generated by Django 2.2.4 on 2020-05-12 13:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("fragmentation", "0020_auto_20190727_0753"),
        ("base", "0011_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Graph",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_base.graph_set+",
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
            options={"abstract": False, "base_manager_name": "objects",},
        ),
        migrations.CreateModel(
            name="MolecularGraph",
            fields=[
                (
                    "graph_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="base.Graph",
                    ),
                ),
                (
                    "frag_sample",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fragmentation.FragSample",
                    ),
                ),
            ],
            options={"abstract": False, "base_manager_name": "objects",},
            bases=("base.graph",),
        ),
    ]
