# Generated by Django 2.2.12 on 2020-11-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabolization', '0011_reaction_tags'),
        ('base', '0013_auto_20200513_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleannotationproject',
            name='reactions',
            field=models.ManyToManyField(to='metabolization.Reaction'),
        ),
        migrations.AlterField(
            model_name='sampleannotationproject',
            name='depth_total',
            field=models.IntegerField(default=1),
        ),
    ]
